#!/bin/bash
mvn clean install
java -jar target/org.kevoree.modeling.c.generator-1.3.2.jar \
  -i src/main/resources/metamodel/kevoree.ecore \
  -t ./kevoree \
  -f src/main/resources/hardcoded/
mkdir kevoree/build
cd kevoree/build
cmake ../
make

